# Generated by Django 5.1.5 on 2025-01-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_student_id_student_roll_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
